version: 2

defaults: &defaults
  docker:
    - image: circleci/node:6-browsers
  environment:
    - DOCKER_IMAGE: "tabit.azurecr.io/reportserver"
  working_directory: ~/reporting-server
jobs:

  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - run: echo "before  git ls"
      - run: ls -a
      - run: git clone https://github.com/inPact/helm-live.git /tmp/helm-live
      - run: ls -lah /tmp
      - run: echo "before ls"
      - run: ls -a
      - run: echo $PWD
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/reporting-server
  build:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: docker build -t "$DOCKER_IMAGE":"${CIRCLE_BRANCH////_}-$(echo $CIRCLE_SHA1 | cut -c -7)" .
      - run: docker login --username $DOCKER_USER --password $DOCKER_PASS tabit.azurecr.io
      - run: docker push "$DOCKER_IMAGE":"${CIRCLE_BRANCH////_}-$(echo $CIRCLE_SHA1 | cut -c -7)"

  deploy:
    <<: *defaults
    steps:
#      - run:
#          name: Avoid hosts unknown for github
#          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker:
          docker_layer_caching: true
      - run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
      - run: chmod 700 get_helm.sh
      - run: ./get_helm.sh
#      - run:
#          name: Avoid hosts unknown for github
#          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: chmod +x .circleci/deploy.sh
      - run: .circleci/deploy.sh

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - checkout_code:
          # We have to explicitly tell CircleCi to run on all tags and branches, or tag commits/pushes will not trigger
          # builds: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution.
          filters:
            branches:
              ignore:
                - dev
                - verification
                - /feature.*/
            tags:
              only: /.*/
      - build:
          filters:
            branches:
              ignore:
                - dev
                - verification
                - /feature.*/
            tags:
              only: /.*/
          requires:
            - checkout_code

      - deploy:
          filters:
            branches:
              ignore:
                - dev
                - verification
                - /feature.*/
            tags:
              only: /.*/
          requires:
            - build
