version: 2

defaults: &defaults
  environment:
    - DOCKER_IMAGE: "tabit.azurecr.io/reportserver"

jobs:

  build:
    <<: *defaults
    docker:
      - image: circleci/node:6-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

      - run:
          command: |
            docker build -t tabit.azurecr.io/reportserver:"$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7)" .
      - run:
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASS tabit.azurecr.io
      - run:
          command: |
            docker push tabit.azurecr.io/reportserver:"$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7)"