version: 2

defaults: &defaults
  docker:
    - image: circleci/node:6-browsers
  environment:
    - DOCKER_IMAGE: "tabit.azurecr.io/reportserver"
  working_directory: ~/reporting-server
jobs:

  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/reporting-server
  build:
    <<: *defaults
    steps:
      - run:
          command: |
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
      - run:
          command: |
            chmod 700 get_helm.sh
      - run:
          command: |
            ./get_helm.sh
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            docker build -t "$DOCKER_IMAGE":"${CIRCLE_BRANCH////_}-$(echo $CIRCLE_SHA1 | cut -c -7)" .
      - run:
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASS tabit.azurecr.io
      - run:
          command: |
            docker push "$DOCKER_IMAGE":"${CIRCLE_BRANCH////_}-$(echo $CIRCLE_SHA1 | cut -c -7)"

  deploy:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            chmod +x .circleci/deploy.sh
      - run:
          command: |
            .circleci/deploy.sh

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - checkout_code:
          # We have to explicitly tell CircleCi to run on all tags and branches, or tag commits/pushes will not trigger
          # builds: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution.
          filters:
            branches:
              ignore:
                - dev
                - verification
                - /feature.*/
            tags:
              only: /.*/
      - build:
          filters:
            branches:
              ignore:
                - dev
                - verification
                - /feature.*/
            tags:
              only: /.*/
          requires:
            - checkout_code

      - deploy:
          filters:
            branches:
              ignore:
                - dev
                - verification
                - /feature.*/
            tags:
              only: /.*/
          requires:
            - build
