apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reporting-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "reporting-server.name" . }}
    helm.sh/chart: {{ include "reporting-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "reporting-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "reporting-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{.Values.containers.command}}
          args: {{.Values.containers.args}}
          ports:
            - containerPort: {{.Values.containers.containerPort}}
          env:
            - name: DATABASE_USER
              value: {{.Values.env.DATABASE_USER}}
            - name: NODE_ENV
              value: {{.Values.env.NODE_ENV}}
            - name: DATABASE_PASSWORD
              value: {{.Values.env.DATABASE_PASSWORD}}
            - name: DATABASE_NAME
              value: {{.Values.env.DATABASE_NAME}}
            - name: ROS_URL
              value: {{.Values.env.ROS_URL}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
