# Default values for reporting-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tabit.azurecr.io/reportserver
  tag: feature_ci-1ca3ce3
  pullPolicy: IfNotPresent
containers:
  command: ["npm"]
  args: ["start"]
  containerPort: 3000
env:
  DATABASE_USER: "chef"
  NODE_ENV: "development"
  DATABASE_PASSWORD: "vbXS3W9x92cdcD9V"
  DATABASE_NAME: "isrProd"
  ROS_URL: "ROS_URL=https://ros-rp-beta.tabit.cloud"
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  internalPort: 3000


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    #kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/tls-acme: "true"
    #name: example
    #namespace: foo
  paths: [/srv]
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

secret:
  name: datapassword
  key: DATABASE_PASSWORD
  value: dmJYUzNXOXg5MmNkY0Q5Vg==


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# If not specified, creates secrets
#existingAirflowSecret: ""